# Generated by Django 3.0.8 on 2020-09-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_salina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_Salina',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employer',
        ),
    ]
