# Generated by Django 3.0.8 on 2020-09-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200922_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin_status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='employee_status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(default=False, verbose_name='employer_status'),
        ),
    ]
