# Generated by Django 3.0.8 on 2020-09-24 17:05

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('expire_date', models.DateField()),
                ('description', models.CharField(max_length=350)),
                ('salary_high', models.IntegerField()),
                ('salary_low', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('job_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.WorkField')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skill_opt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerData',
            fields=[
                ('userName', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('userHeader', models.CharField(max_length=100)),
                ('theme', models.CharField(blank=True, max_length=10)),
                ('profilePicture', models.CharField(max_length=250)),
                ('shadowText', models.CharField(max_length=100)),
                ('firstIntro', models.CharField(max_length=125)),
                ('secondIntro', models.CharField(max_length=250)),
                ('projects', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), blank=True, size=None), blank=True, size=None)),
                ('socialLinks', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), blank=True, size=None), blank=True, size=None)),
                ('visit', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('totalRating', models.IntegerField(default=0)),
                ('skill_opt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Skill')),
            ],
        ),
    ]
