# Generated by Django 3.0.8 on 2020-09-28 10:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20200926_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerdata',
            name='id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employerdata',
            name='projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='employerdata',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='employerdata',
            name='skills_opt',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='employerdata',
            name='socialLinks',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
