# Generated by Django 3.0.8 on 2020-09-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_auto_20200928_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
