# Generated by Django 3.0.8 on 2020-09-28 11:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_jobs_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='skills_opt',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
