# Generated by Django 3.0.8 on 2020-09-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_auto_20200928_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
