# Generated by Django 3.0.8 on 2020-09-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_jobs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerdata',
            name='firstIntro',
            field=models.CharField(default='## Know more about us. ##', max_length=125),
        ),
        migrations.AlterField(
            model_name='employerdata',
            name='profilePicture',
            field=models.CharField(default='/static/frontend/user.png', max_length=250),
        ),
        migrations.AlterField(
            model_name='employerdata',
            name='secondIntro',
            field=models.CharField(default='## Look at our projects and jobs we provide. ##', max_length=250),
        ),
        migrations.AlterField(
            model_name='employerdata',
            name='shadowText',
            field=models.CharField(default='We are well established company/ new startups/..............', max_length=100),
        ),
        migrations.AlterField(
            model_name='employerdata',
            name='theme',
            field=models.CharField(blank=True, default='white', max_length=10),
        ),
        migrations.AlterField(
            model_name='employerdata',
            name='userHeader',
            field=models.CharField(default='Welcome to our official page.', max_length=100),
        ),
    ]
