# Generated by Django 3.1.1 on 2020-10-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_employerdata_ratedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
