# Generated by Django 3.0.8 on 2020-08-22 16:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='userHeader',
            field=models.CharField(default='HI', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), blank=True, size=None), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='socialLinks',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), blank=True, size=None), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='theme',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
