# Generated by Django 3.0.8 on 2020-08-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200822_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='visit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='userName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
