# Generated by Django 3.0.8 on 2020-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200921_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='visit',
            field=models.IntegerField(default=0),
        ),
    ]
