# Generated by Django 3.0.8 on 2020-09-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200921_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='rating',
        ),
    ]
