# Generated by Django 3.0.8 on 2020-09-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_userdata_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='visit',
        ),
    ]
