# Generated by Django 3.0.8 on 2020-09-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_userdata_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='visit',
            field=models.IntegerField(default=0),
        ),
    ]
