# Generated by Django 3.0.8 on 2020-09-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200921_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='rating',
        ),
    ]
