# Generated by Django 3.0.8 on 2020-09-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200823_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
