# Generated by Django 3.0.8 on 2020-09-24 17:25

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('accounts', '0001_initial'),
        ('database', '0012_auto_20200924_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData1',
            fields=[
                ('id', models.IntegerField(unique=True)),
                ('userName', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('userHeader', models.CharField(max_length=100)),
                ('theme', models.CharField(blank=True, max_length=10)),
                ('profilePicture', models.CharField(max_length=250)),
                ('shadowText', models.CharField(max_length=100)),
                ('firstIntro', models.CharField(max_length=125)),
                ('secondIntro', models.CharField(max_length=250)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, size=None)),
                ('socialLinks', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), blank=True, size=None), blank=True, size=None)),
                ('projects', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), blank=True, size=None), blank=True, size=None)),
                ('visit', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('totalRating', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('interest_opt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.WorkField')),
                ('skill_opt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Skill')),
            ],
        ),
    ]
