# Generated by Django 3.0.8 on 2020-09-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_userdata1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
