# Generated by Django 3.0.8 on 2020-09-24 17:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
        ('database', '0014_delete_userdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData1',
            new_name='UserData',
        ),
    ]
