# Generated by Django 3.0.8 on 2020-09-26 08:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20200924_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='interest_opt',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='skill_opt',
        ),
        migrations.AddField(
            model_name='userdata',
            name='interest_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='userdata',
            name='skills_opt',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
