# Generated by Django 3.0.8 on 2020-09-28 10:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20200928_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='socialLinks',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
