# Generated by Django 3.0.8 on 2020-09-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20200929_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
