# Generated by Django 3.0.8 on 2020-10-01 10:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20200930_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='ratedUsers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
